services:
  api:
    build: .
    container_name: back-api-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - .:/app
